---
- hosts: k8s_master:k8s_nodes
  gather_facts: False
  tasks:
    - name: Installing nfs-common.
      become: yes
      apt:
          name: nfs-common


- hosts: k8s_master
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ../../vars.yml
            
      - name: Deploying NFS Provisioner manifests to Kubernetes
        become: yes
        k8s:
            definition: "{{ lookup('template', '../../files/templates/NFS/{{ item }}') | from_yaml }}"        
        with_items:
            - "ns_nfs_provisioner.yml.j2"
            - "cr_nfs_provisioner.yml.j2"
            - "crb_nfs_provisioner.yml.j2"
            - "sa_nfs_provisioner.yml.j2"
            - "rb_nfs_provisioner.yml.j2"
            - "role_nfs_provisioner.yml.j2"
            - "dep_nfs_provisioner.yml.j2"
            - "sc_nfs_provisioner.yml.j2"
