---
- hosts: k8s_master:k8s_nodes
  gather_facts: False
  tasks:
      - name: Including the variables.
        include_vars:
            file: ../../vars.yml

      - name: Waiting for Debian to finish performing automatic updates before continuing.
        script: ../../files/bash_scripts/monitor_automatic_updates_status.sh

      - name: Setting Nameservers 
        shell: sudo sh -c "echo 'nameserver 192.168.40.1' > /etc/resolv.conf"
        
      - name: Performing a Package Upgrade.
        become: yes
        apt:
            name: '*'
            state: latest

      - name: Installing the base packages.
        become: yes
        apt:
            name: ['apt-transport-https', 'ca-certificates', 'curl', 'haveged', 'gnupg2', 'openssl', 'python-pip', 'qemu-guest-agent', 'software-properties-common', 'arptables', 'ebtables']

      - name: Configuring the nodes to use legacy iptables for compatibility with Kubernetes.
        become: yes
        alternatives:
            name: "{{ item }}"
            path: /usr/sbin/{{ item }}-legacy
        with_items:
            - "iptables"
            - "ip6tables"
            - "arptables"
            - "ebtables"

      - name: Adding the necessary GPG keys.
        become: yes
        apt_key: 
            url: "{{ item }}"
        with_items:
            - "https://download.docker.com/linux/debian/gpg"
            - "https://packages.cloud.google.com/apt/doc/apt-key.gpg"

      - name: Adding the necessary Apt repositories.
        become: yes
        apt_repository:
            repo: "{{ item }}"
        with_items:
            - "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
            - "deb https://apt.kubernetes.io/ kubernetes-xenial main"

      - name: Updating the package repositories.
        become: yes
        apt: 
            update_cache: yes

      - name: Installing the required packages to bootstrap a kubernetes cluster.
        become: yes
        apt:
            name: ['docker-ce', 'kubelet', 'kubeadm', 'kubectl']

      - name: Installing the necessary Python library dependencies to use the `k8s` Ansible module.
        become: yes
        pip:
            name: ['openshift', 'kubernetes', 'pyyaml', 'requests']
            extra_args: --upgrade

      - name: Enabling the necessary Systemd modules.
        become: yes
        systemd: 
            state: started
            name: "{{ item }}"
            enabled: yes
        with_items:
            - "docker"
            - "kubelet"
            - "qemu-guest-agent"
            - "haveged"

      - name: Removing the DHCP lines for eth0 from the interfaces file.
        become: yes
        lineinfile:
            state: absent
            path: /etc/network/interfaces
            line: iface eth0 inet dhcp

      - name: Rebooting the OS to switch to cloud-init provided network configuration & finalize any necessary package upgrades.
        become: yes
        reboot:
